Form begining
RoyNyaga/microverse_html_form_project pull request #1
Opened 2019-07-12 20:18 UTC by RoyNyaga

2019-07-14 01:17 UTC, bolah2009 requested changes
# Great Work Team! :clap:

This was an excellent effort!  :ok_hand: 
You are almost there! Only a few changes required. :blush:

To make the review even much easier for you, below are the checklist to consider the project `complete`  as it must satisfy the following points:

#### Sign In Button

:recycle:  It has a Sign In button at the top right corner

#### Intuit logo

:heavy_check_mark: It shows the Intuit logo above the form

:heavy_check_mark: The intuit logo is an embedded image that is horizontally centered

#### Intuit products

:heavy_check_mark: There is a dedicated container for displaying intuit's products (mint, quickbox, turbotax)

:heavy_check_mark: The products are displayed in a single row

:heavy_check_mark: The products row is under the Intuit logo and above the form

:heavy_check_mark: It shows the Mint logo and text (logo on the left, text on the right)

:heavy_check_mark: It shows the Quickbooks logo and text (logo on the left, text on the right)

:heavy_check_mark: It shows the Turbotax logo and text (logo on the left, text on the right)

#### Form

:heavy_check_mark: It has a `<form>` element

:heavy_check_mark: The text is horizontally centered (Except for `<input>` labels)

##### Top

:heavy_check_mark: It has the title `Create an Intuit account`

:heavy_check_mark: It has a description: `One account for everything Intuit, including Mint`

:recycle:  It has a `Learn More` link

##### Middle 

:heavy_check_mark:  All the labels are displayed above the input

:heavy_check_mark:  It has an `<input>` of type `email` and a label `Email address`

:recycle:  It has an `<input>` of type `tel` and a label `Phone`.

:recycle:   It has an `<input>` of type `password` and a label `Password`.

:heavy_check_mark:  It has a submit button that matches the style of the original page (Blue background, white text)

##### Bottom

:recycle:   It has a disclaimer text that matches the context and style of the original page

Keep up the good work and best of luck on the next submission. 👍


Happy Coding!  :dizzy: and Have a Nice Day :smile:

Cheers,  
Bola

2019-07-14 01:17 UTC, bolah2009 commented on css/style.css
> +	/*position: relative;
`REQUIRED`

Consider deleting commented out codes.

2019-07-14 01:17 UTC, bolah2009 commented on css/style.css
> +	/*padding: 30px 0px 00px 30px;*/
`REQUIRED`

Consider deleting commented out codes.

2019-07-14 01:17 UTC, bolah2009 commented on css/style.css
> +/*	background-color: green;*/
`REQUIRED`

Consider deleting commented out codes.

2019-07-14 01:17 UTC, bolah2009 commented on css/style.css
> +	padding-bottom: -100px;
`REQUIRED` 

`-100px` is an invalid value for  `padding-bottom` property. Negative values are not allowed for this property.

2019-07-14 01:17 UTC, bolah2009 commented on css/style.css
> +	background-color: #ffffff;
`SUGGESTION`

Please, fix the indentation. :blush:
A good indentation is fundamental for good readability of the code.
Many IDE  can help you with this task.
This is VS Code, for example as shown below using [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode):

![Screenshot of how to format code using VS Code](https://res.cloudinary.com/bolaah/image/upload/v1563045186/github-microverse-project/code-reviews/code-review002.gif)

2019-07-14 01:17 UTC, bolah2009 commented on debug.log
> +[0712/175608.107:ERROR:crash_report_database_win.cc(469)] failed to stat report
`SUGGESTION`

Please, consider deleting this file since it has nothing to do with the project.

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +<html>
`SUGGESTION`

Consider adding `lang="en"` (or variant) to the `html` start tag, this is good for internationalisation. Also, check this [link for more info](https://www.w3.org/International/questions/qa-html-language-declarations#basics)

Take advantage of [HTML CHECKER](https://validator.w3.org) by checking your code with this online tool. It spots out common mistakes/omission in HTML codes. :+1:

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +<!DOCTYPE>
`SUGGESTION`

Replace `<!DOCTYPE>` with `<!DOCTYPE html>`. Also, check your code with [HTML Checker](https://validator.w3.org/nu/#textarea).

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +			<p><ts style="color:black;">Already have an intuit account?</ts> <br> I forgot my User ID or Password </p>
`REQUIRED`

Consider using a linked CSS style rather than in-line and also `ts` is an invalid HTML element in this context.

Take advantage of [HTML CHECKER](https://validator.w3.org) by checking your code with this online tool. It spots out common mistakes/omission in HTML codes. :+1:

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +			<span class="ius-white-lock-img"></span><button name="signin" type="signin" class="button" ><img src="images/lock.png" alt="lock no found" /> &nbsp&nbsp<b>Sign in</b></button>
`REQUIRED`

`type="signin"` is an invalid atrribute for `<button>` element, 

Take advantage of [HTML CHECKER](https://validator.w3.org) by checking your code with this online tool. It spots out common mistakes/omission in HTML codes. :+1:

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +	<img class="logo" src="images/logo.png" alt="intuit logo">
`AWESOME`

Nice job, :clap: :star2:  adding an `alt` attribute to the `<img>` element, this is a very important accessibility attribute.
`Examples of scenarios where users benefit from text alternatives for images` are listed below and could also be found [here](https://www.w3.org/TR/html51/semantics-embedded-content.html#alt-text)

- They have a very slow connection and are browsing with images disabled.
- They have a vision impairment and use text to speech software.
- They have a cognitive impairment and use text to speech software.
- They are using a text-only browser.
- They are listening to the page being read out by a voice Web browser.
- They have images disabled to save on download costs.
- They have problems loading images or the source of an image is wrong.


##### SOURCE: [W3C Recommendation (Embedded Content)](https://www.w3.org/TR/html51/semantics-embedded-content.html#alt-text)

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +		<p class="above-text">One account for everything Intuit, including Mint. <br> <a href="#"><small class="above-text">learn more</small></a></p>
`REQUIRED`

It should have a `Learn More` link as shown below:

![Mint.com Signup page screenshot](https://res.cloudinary.com/bolaah/image/upload/v1563061683/github-microverse-project/code-reviews/004.gif)

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +    <input type="email" class="form-input" id="email" name="email" placeholder="Your Email">
`AWESOME`

Good job associating the `<label>` with an `<input>` element. :clap: :+1: 

> #### Associating a `<label>` with an `<input>` element offers some major advantages:
> 
> - The label text is not only visually associated with its corresponding text input; it is programmatically associated with it too. This means that, for example, a screen reader will read out the label when the user is focused on the form input, making it easier for an assistive technology user to understand what data should be entered.
> 
> - You can click the associated label to focus/activate the input, as well as the input itself. This increased hit area provides an advantage to anyone trying to activate the input, including those using a touch-screen device.

Alternatively, you can nest the `<input>` directly inside the `<label>` like this: 

``` html
  <label for="email">Email address <br>
       <input type="email" name="email" id="email">
  </label> 
```


You can learn more [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +    <input type="number" class="form-input" id="lnumber" name="number" placeholder="Phone number"><small>Standard call, messaging or data rates may apply.</small></br>
`REQUIRED`

Consider using `type="tel"` for Phone number input, this makes adding custom validation and handling of phone numbers more convenient among other dedicated features.

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +    <input type="number" class="form-input" id="lpassword" name="password" placeholder="Enter password">
`REQUIRED`

Consider using `type="password"` for Password input, this makes adding custom validation and handling of passwords more convenient among other dedicated features.

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +</html>
Please check out [this comment]() on indentation.

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +</main>
`REQUIRED` 

Consider using `<main>` to cover the main section of the page, that is extending it until the `<footer>` element, this shows the dominant content of the `<body>` of a document. More on `<main>` [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main).

2019-07-14 01:17 UTC, bolah2009 commented on index.html
> +		<div class="nav-button">
`REQUIRED`

Sign in button is not properly aligned with `100%` Zoom. See below:

![Sign up button](https://res.cloudinary.com/bolaah/image/upload/v1563066685/github-microverse-project/code-reviews/005.gif)

2019-07-16 05:19 UTC, Ispirett commented
Great work with the changes made so far :100: However there are some issues that need addressing before project completion. 
- [ ] use this tool , upload your html file and fix these issues https://validator.w3.org/ .
- [ ] **OPTIONAL** make the grey background with the text ** Invisible reCAPTCHA by Google Privacy Policy and Terms of Use.** fill the main tag like the original site

2019-07-17 14:27 UTC, merged